.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge_13 - Debug ]----------"
	@cd "Challenge_13" && "$(MAKE)" -f  "Challenge_13.mk"
clean:
	@echo "----------Cleaning project:[ Challenge_13 - Debug ]----------"
	@cd "Challenge_13" && "$(MAKE)" -f  "Challenge_13.mk" clean
