.PHONY: clean All

All:
	@echo "----------Building project:[ ClassesObjects - Debug ]----------"
	@cd "ClassesObjects" && "$(MAKE)" -f  "ClassesObjects.mk"
clean:
	@echo "----------Cleaning project:[ ClassesObjects - Debug ]----------"
	@cd "ClassesObjects" && "$(MAKE)" -f  "ClassesObjects.mk" clean
