.PHONY: clean All

All:
	@echo "----------Building project:[ quiz_1 - Debug ]----------"
	@cd "quiz_1" && "$(MAKE)" -f  "quiz_1.mk"
clean:
	@echo "----------Cleaning project:[ quiz_1 - Debug ]----------"
	@cd "quiz_1" && "$(MAKE)" -f  "quiz_1.mk" clean
